### ISSUE TITLE
Got a lower test_metric

### ISSUE THREAD

**Issue by ghost** [GanjinZero/ICD-MSMN#12]
Hi, thanks for the great work. 

After setting the embedding path and trained model path according to the readme, I ran the eval_model.py on the mimic-3 full dataset and got the following test results:

<img width="576" alt="image" src="https://github.com/GanjinZero/ICD-MSMN/assets/162932682/804001b3-fe26-41a0-ad46-537d0752e670">

But these results are lower than the results in the paper, I don't know what the reason is, is there a problem with my settings？

Looking forward to your reply, Best wishes.

**Comment by GanjinZero** [comment]
I think if you use my trained model, you do not need embedding path. The AUC seems very odd.

**Comment by ghost** [comment]
Thank you for your reply, I think the problem is solved, I ran main.py trained a new model and got very close results.
