### ISSUE TITLE
macro_f1 implementation issue

### ISSUE THREAD

**Issue by whaleloops** [GanjinZero/ICD-MSMN#13]
The macro_f1 implementation [here](https://github.com/GanjinZero/ICD-MSMN/blob/c9bccff9a42ba2eefe68f7c4067766982c0e8bf7/evaluation.py#L76) is not consistent with the standard here in page 10 https://web.stanford.edu/class/cs224u/2021/slides/cs224u-2021-methods-part2-handout.pdf
![image](https://github.com/GanjinZero/ICD-MSMN/assets/31370581/721b5cf8-4aea-4313-9b51-3de4724ea090)

**Comment by GanjinZero** [comment]
copied from https://github.com/jamesmullenbach/caml-mimic/blob/master/evaluation.py
