### ISSUE TITLE
label_feat cannot be reshaped to [12, 4, 512]

### ISSUE THREAD

**Issue by dululuxi** [GanjinZero/ICD-MSMN#2]
![image](https://user-images.githubusercontent.com/95865726/167382178-535a851a-bc0d-47b8-ba89-37767bcddea1.png)
![image](https://user-images.githubusercontent.com/95865726/167382255-0603829f-6990-470f-be94-18a9c34d1517.png)

**Comment by GanjinZero** [comment]
How you run the code? Do you modify any files?

**Comment by dululuxi** [comment]
> How you run the code? Do you modify any files?

Thanks, I found that some parameters were set incorrectly when I ran
