### ISSUE TITLE
Lack of 'word2vec_sg0_100.model.wv.vectors.npy’ in Word Embedding

### ISSUE THREAD

**Issue by czh007** [GanjinZero/ICD-MSMN#6]
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/38771857/172032370-f4318638-8d1c-4e69-bd53-0b470e4f1b31.png">
Dear   Author:    @GanjinZero 
Lacking of 'word2vec_sg0_100.model.wv.vectors.npy’ in Word Embedding，while word2vec_sg0_100.model is ready.

**Comment by GanjinZero** [comment]
https://github.com/aehrc/LAAT/blob/master/data/embeddings/word2vec_sg0_100.model.wv.vectors.npy
