### ISSUE TITLE
A mistake: line 118 in main.py in run

### ISSUE THREAD

**Issue by freshjarman** [GanjinZero/ICD-MSMN#7]
![image](https://user-images.githubusercontent.com/43328056/172149952-8359d422-d1ab-42e6-9109-1a4863f64f82.png)

I met a mistake: line 118 in main.py, should i rewrite it like `best_train_metric, _, threshold_ = eval_func()` ?

PS: line 83 in main.py, the same mistake

**Comment by GanjinZero** [comment]
you are right.

**Comment by GanjinZero** [comment]
fix it
